# Generated by Django 6.0a1 on 2025-12-13 16:39

import users.permissions
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.permissions.CustomUserManager()),
            ],
        ),
    ]
